version: '3'

services:
  database:
    container_name: tech-diversity-db
    image: "postgres"
    environment:
        - POSTGRES_DB=tech_diversity
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: